POST http://localhost:8000/api/chat/gpt-3
Content-Type: application/json
Token: test_token

{
  "senderId": "test_sender_id",
  "text": {
    "content": "测试"
  },
  "sessionWebhook": "https://baidu.com",
  "msgId": "test_msg_id"
}